# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDesign/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 259)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 79, 16))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 40, 741, 209))
        self.groupBox.setObjectName("groupBox")
        self.tdname = QtWidgets.QTextEdit(self.groupBox)
        self.tdname.setGeometry(QtCore.QRect(11, 52, 271, 31))
        self.tdname.setObjectName("tdname")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setGeometry(QtCore.QRect(11, 110, 112, 20))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.labeltdname = QtWidgets.QLabel(self.groupBox)
        self.labeltdname.setGeometry(QtCore.QRect(11, 33, 184, 16))
        self.labeltdname.setObjectName("labeltdname")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(11, 90, 142, 17))
        self.checkBox.setObjectName("checkBox")
        self.tdmainbody = QtWidgets.QTextEdit(self.groupBox)
        self.tdmainbody.setGeometry(QtCore.QRect(350, 30, 381, 101))
        self.tdmainbody.setObjectName("tdmainbody")
        self.emailInput = QtWidgets.QLineEdit(self.groupBox)
        self.emailInput.setGeometry(QtCore.QRect(130, 140, 200, 20))
        self.emailInput.setObjectName("emailInput")
        self.emailLabel = QtWidgets.QLabel(self.groupBox)
        self.emailLabel.setGeometry(QtCore.QRect(130, 120, 111, 16))
        self.emailLabel.setObjectName("emailLabel")
        self.sendButton = QtWidgets.QPushButton(self.groupBox)
        self.sendButton.setGeometry(QtCore.QRect(340, 140, 100, 25))
        self.sendButton.setObjectName("sendButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Advanced To Do"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.labeltdname.setText(_translate("MainWindow", "Краткое название для напоминания"))
        self.checkBox.setText(_translate("MainWindow", "Получить уведомление"))
        self.emailInput.setPlaceholderText(_translate("MainWindow", "Введите email получателя"))
        self.emailLabel.setText(_translate("MainWindow", "Email получателя:"))
        self.sendButton.setText(_translate("MainWindow", "Отправить"))
