# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDesign/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from constants import COLORS, FONTS, WINDOW_SIZE, PADDING, SPACING, TEXTS, INPUT_FIELDS


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(WINDOW_SIZE)
        MainWindow.setStyleSheet(f"background-color: {COLORS['background']};")

        # Центральный виджет
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Главный заголовок
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(PADDING, PADDING, 300, 30))
        self.label.setFont(FONTS['title'])
        self.label.setStyleSheet(f"color: {COLORS['primary']};")
        self.label.setObjectName("label")

        # Группа элементов
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(
            PADDING, 60, 
            WINDOW_SIZE.width() - 2*PADDING,
            WINDOW_SIZE.height() - 80
        ))
        self.groupBox.setFont(FONTS['subtitle'])
        self.groupBox.setStyleSheet(f"""
            QGroupBox {{
                border: 2px solid {COLORS['primary']};
                border-radius: 8px;
                margin-top: 10px;
            }}
            QGroupBox::title {{
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 5px;
            }}
        """)
        self.groupBox.setObjectName("groupBox")

        # Поле названия
        self.labeltdname = QtWidgets.QLabel(self.groupBox)
        self.labeltdname.setGeometry(INPUT_FIELDS['name']['label_geometry'])
        self.labeltdname.setFont(FONTS['regular'])
        self.labeltdname.setObjectName("labeltdname")

        self.tdname = QtWidgets.QTextEdit(self.groupBox)
        self.tdname.setGeometry(INPUT_FIELDS['name']['geometry'])
        self.tdname.setFont(FONTS['regular'])
        self.tdname.setStyleSheet(f"""
            QTextEdit {{
                border: 1px solid #ccc;
                border-radius: 4px;
                padding: 5px;
            }}
        """)
        self.tdname.setObjectName("tdname")

        # Поле подробного описания
        self.detailsLabel = QtWidgets.QLabel(self.groupBox)
        self.detailsLabel.setGeometry(INPUT_FIELDS['details']['label_geometry'])
        self.detailsLabel.setFont(FONTS['regular'])
        self.detailsLabel.setObjectName("detailsLabel")

        self.tdDetails = QtWidgets.QTextEdit(self.groupBox)
        self.tdDetails.setGeometry(INPUT_FIELDS['details']['input_geometry'])
        self.tdDetails.setFont(FONTS['regular'])
        self.tdDetails.setStyleSheet(f"""
            QTextEdit {{
                border: 1px solid #ccc;
                border-radius: 4px;
                padding: 5px;
            }}
        """)
        self.tdDetails.setPlaceholderText(TEXTS['details_placeholder'])
        self.tdDetails.setObjectName("tdDetails")

        # Чекбокс уведомления
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(INPUT_FIELDS['notification']['geometry'])
        self.checkBox.setFont(FONTS['regular'])
        self.checkBox.setObjectName("checkBox")

        # Поле даты и времени
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setGeometry(INPUT_FIELDS['datetime']['geometry'])
        self.dateTimeEdit.setFont(FONTS['regular'])
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setStyleSheet(f"""
            QDateTimeEdit {{
                border: 1px solid #ccc;
                border-radius: 4px;
                padding: 5px;
            }}
        """)
        self.dateTimeEdit.setObjectName("dateTimeEdit")

        # Поля для email
        self.emailLabel = QtWidgets.QLabel(self.groupBox)
        self.emailLabel.setGeometry(INPUT_FIELDS['email']['label_geometry'])
        self.emailLabel.setFont(FONTS['regular'])
        self.emailLabel.setObjectName("emailLabel")

        self.emailInput = QtWidgets.QLineEdit(self.groupBox)
        self.emailInput.setGeometry(INPUT_FIELDS['email']['input_geometry'])
        self.emailInput.setFont(FONTS['regular'])
        self.emailInput.setStyleSheet(f"""
            QLineEdit {{
                border: 1px solid #ccc;
                border-radius: 4px;
                padding: 5px;
            }}
        """)
        self.emailInput.setObjectName("emailInput")

        # Кнопка отправки
        self.sendButton = QtWidgets.QPushButton(self.groupBox)
        self.sendButton.setGeometry(INPUT_FIELDS['send_button']['geometry'])
        self.sendButton.setFont(FONTS['regular'])
        self.sendButton.setStyleSheet(f"""
            QPushButton {{
                background-color: {COLORS['primary']};
                color: {COLORS['light_text']};
                border: none;
                border-radius: 4px;
                padding: 5px 10px;
            }}
            QPushButton:hover {{
                background-color: {COLORS['secondary']};
            }}
        """)
        self.sendButton.setObjectName("sendButton")

        # Основное поле для списка напоминаний
        self.tdmainbody = QtWidgets.QTextEdit(self.groupBox)
        self.tdmainbody.setGeometry(INPUT_FIELDS['main_body']['geometry'])
        self.tdmainbody.setMinimumHeight(INPUT_FIELDS['main_body']['min_height'])
        self.tdmainbody.setStyleSheet(f"""
            QTextEdit {{
                border: 1px solid #ccc;
                border-radius: 4px;
                padding: 15px;
                font-size: 12px;
            }}
        """)
        self.tdmainbody.setReadOnly(True)
        self.tdmainbody.setObjectName("tdmainbody")

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", TEXTS['window_title']))
        self.label.setText(_translate("MainWindow", TEXTS['main_label']))
        self.groupBox.setTitle(_translate("MainWindow", TEXTS['group_box_title']))
        self.labeltdname.setText(_translate("MainWindow", TEXTS['name_label']))
        self.detailsLabel.setText(_translate("MainWindow", TEXTS['details_label']))
        self.checkBox.setText(_translate("MainWindow", TEXTS['notification_text']))
        self.emailLabel.setText(_translate("MainWindow", TEXTS['email_label']))
        self.emailInput.setPlaceholderText(_translate("MainWindow", TEXTS['email_placeholder']))
        self.sendButton.setText(_translate("MainWindow", TEXTS['send_button']))
        self.tdmainbody.setPlaceholderText(_translate("MainWindow", TEXTS['body_placeholder']))
        self.tdDetails.setPlaceholderText(_translate("MainWindow", TEXTS['details_placeholder']))